import { WeatherData } from '../types/ghostly';

export const CITIES_WEATHER: Record<string, WeatherData> = {
  'Ho Chi Minh City': {
    city: 'Ho Chi Minh City',
    country: 'Vietnam',
    tempC: 31,
    condition: 'Sunny with soft clouds',
    icon: 'Sun',
    feelsLikeC: 35,
    humidity: 74,
    windKmh: 12,
    uvIndex: 8,
    forecast: [
      { day: 'Sat', high: 32, low: 25, icon: 'Sun', condition: 'Sunny' },
      { day: 'Sun', high: 33, low: 26, icon: 'CloudSun', condition: 'Partly Cloudy' },
      { day: 'Mon', high: 30, low: 24, icon: 'CloudRain', condition: 'Scattered Showers' },
      { day: 'Tue', high: 31, low: 25, icon: 'CloudSun', condition: 'Partly Cloudy' },
      { day: 'Wed', high: 32, low: 25, icon: 'Sun', condition: 'Clear' },
    ],
    isOnline: true,
    lastUpdated: new Date(),
  },
  Tokyo: {
    city: 'Tokyo',
    country: 'Japan',
    tempC: 19,
    condition: 'Clear Breeze',
    icon: 'Sun',
    feelsLikeC: 18,
    humidity: 52,
    windKmh: 16,
    uvIndex: 5,
    forecast: [
      { day: 'Sat', high: 20, low: 13, icon: 'Sun', condition: 'Clear' },
      { day: 'Sun', high: 22, low: 15, icon: 'Sun', condition: 'Sunny' },
      { day: 'Mon', high: 18, low: 12, icon: 'Cloud', condition: 'Overcast' },
      { day: 'Tue', high: 17, low: 11, icon: 'CloudRain', condition: 'Light Rain' },
      { day: 'Wed', high: 21, low: 14, icon: 'CloudSun', condition: 'Partly Cloudy' },
    ],
    isOnline: true,
    lastUpdated: new Date(),
  },
  Berlin: {
    city: 'Berlin',
    country: 'Germany',
    tempC: 14,
    condition: 'Gentle Autumn Cloud',
    icon: 'Cloud',
    feelsLikeC: 13,
    humidity: 68,
    windKmh: 18,
    uvIndex: 3,
    forecast: [
      { day: 'Sat', high: 15, low: 8, icon: 'Cloud', condition: 'Cloudy' },
      { day: 'Sun', high: 16, low: 9, icon: 'CloudSun', condition: 'Sun breaks' },
      { day: 'Mon', high: 13, low: 7, icon: 'CloudRain', condition: 'Drizzle' },
      { day: 'Tue', high: 12, low: 6, icon: 'Wind', condition: 'Breezy' },
      { day: 'Wed', high: 14, low: 8, icon: 'Cloud', condition: 'Overcast' },
    ],
    isOnline: true,
    lastUpdated: new Date(),
  },
  'San Francisco': {
    city: 'San Francisco',
    country: 'United States',
    tempC: 17,
    condition: 'Coastal Fog Clearing',
    icon: 'CloudSun',
    feelsLikeC: 16,
    humidity: 78,
    windKmh: 22,
    uvIndex: 6,
    forecast: [
      { day: 'Sat', high: 18, low: 12, icon: 'CloudSun', condition: 'Fog to Sun' },
      { day: 'Sun', high: 19, low: 12, icon: 'Sun', condition: 'Sunny' },
      { day: 'Mon', high: 17, low: 11, icon: 'Wind', condition: 'Windy' },
      { day: 'Tue', high: 18, low: 12, icon: 'Sun', condition: 'Clear' },
      { day: 'Wed', high: 19, low: 13, icon: 'Sun', condition: 'Clear' },
    ],
    isOnline: true,
    lastUpdated: new Date(),
  },
};
